INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:44:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:44:50] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:44:50] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:44:50] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
ERROR:Zortom:Exception on / [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 44, in home
    image_paths = get_pic_paths(app.config['QR_LIB'], app.config["IMAGE_EXTS"])
  File "/home/c/Code/github/tFlask-Image-Gallery/koon.py", line 15, in get_pic_paths
    files=glob.glob(Path(instance_path,ext))
  File "/usr/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.8/glob.py", line 43, in _iglob
    if not has_magic(pathname):
  File "/usr/lib/python3.8/glob.py", line 151, in has_magic
    match = magic_check.search(s)
TypeError: expected string or bytes-like object
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:48:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:53:14] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:53:14] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:53:14] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:53:14] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[32mGET /cdn//home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579355379955559192.168.2.15.jpg HTTP/1.1[0m" 308 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[32mGET /cdn//home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg HTTP/1.1[0m" 308 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[32mGET /cdn//home/c/Code/github/tFlask-Image-Gallery/instance/qrs/myQRcODE.jpg HTTP/1.1[0m" 308 -
ERROR:Zortom:Exception on /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579355379955559192.168.2.15.jpg [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 54, in download_file
    dir,filename = os.path.split(decode(filepath))
  File "app.py", line 38, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Non-hexadecimal digit found
ERROR:Zortom:Exception on /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/myQRcODE.jpg [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 54, in download_file
    dir,filename = os.path.split(decode(filepath))
  File "app.py", line 38, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Odd-length string
ERROR:Zortom:Exception on /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 54, in download_file
    dir,filename = os.path.split(decode(filepath))
  File "app.py", line 38, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Non-hexadecimal digit found
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[35m[1mGET /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579355379955559192.168.2.15.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[35m[1mGET /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/myQRcODE.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:49] "[35m[1mGET /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:54] "[32mGET /cdn//home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg HTTP/1.1[0m" 308 -
ERROR:Zortom:Exception on /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 54, in download_file
    dir,filename = os.path.split(decode(filepath))
  File "app.py", line 38, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Non-hexadecimal digit found
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 16:54:54] "[35m[1mGET /cdn/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/1660579832114586146192.168.2.15.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
ERROR:Zortom:Exception on / [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 49, in home
    image_paths = encode(get_pic_paths(app.config['QR_LIB'], app.config["IMAGE_EXTS"]))
  File "app.py", line 34, in encode
    if isinstance(x,list()):
TypeError: isinstance() arg 2 must be a type or tuple of types
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:06:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
ERROR:Zortom:Exception on / [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 49, in home
    image_paths = encode(get_pic_paths(app.config['QR_LIB'], app.config["IMAGE_EXTS"]))
  File "app.py", line 36, in encode
    ret.append(encode(i))
  File "app.py", line 38, in encode
    ret=binascii.hexlify(x.encode('utf-8')).decode()
AttributeError: 'PosixPath' object has no attribute 'encode'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:07:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 17:08:05] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://192.168.5.2:8456 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 21:18:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET /static/style.css HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET /static/script.js HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:10:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:21:53] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:23:15] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:24:27] "[33mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 64, in download_file
    return send_file(Path(app.instance_path,'qrs'), filename, as_attachment=False)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/werkzeug/utils.py", line 489, in send_file
    file = open(path, "rb")  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/home/c/Code/github/tFlask-Image-Gallery/instance/qrs'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 64, in download_file
    return send_file(Path(app.instance_path,'qrs'), filename, as_attachment=False)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/werkzeug/utils.py", line 489, in send_file
    file = open(path, "rb")  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/home/c/Code/github/tFlask-Image-Gallery/instance/qrs'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 64, in download_file
    return send_file(Path(app.instance_path,'qrs'), filename, as_attachment=False)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/werkzeug/utils.py", line 489, in send_file
    file = open(path, "rb")  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/home/c/Code/github/tFlask-Image-Gallery/instance/qrs'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:25:14] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:26:09] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:14] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067ss [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in download_file
    filename = decode(filepath)
  File "app.py", line 43, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Non-hexadecimal digit found
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 22:40:25] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d795152634f44452e6a7067ss HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:13] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:13] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:14] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:14] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:14] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:14] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7064447 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in download_file
    filename = decode(filepath)
  File "app.py", line 43, in decode
    return binascii.unhexlify(x.encode('utf-8')).decode()
binascii.Error: Odd-length string
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:32:38] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7064447 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7064447 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 73, in download_file
    return send_file(Path(app.instance_path,'qrs/k404', 'result.jpg'), as_attachment=False)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/werkzeug/utils.py", line 438, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/k404/result.jpg'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:29] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7064447 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:35] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7097 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 73, in download_file
    return send_file(Path(app.instance_path,'qrs/k404', 'result.jpg'), as_attachment=False)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/helpers.py", line 610, in send_file
    return werkzeug.utils.send_file(
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/werkzeug/utils.py", line 438, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/c/Code/github/tFlask-Image-Gallery/instance/qrs/k404/result.jpg'
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:34:48] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7097 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:25] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7097 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:35] "GET /cdn/2f686fjljhgkhg2f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7097 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:40] "[33mGET /cdn/ HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:35:44] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:36:26] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:36:34] "GET /cdn/2f686f6gfjg2f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [17/Aug/2022 23:59:51] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 78, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 78, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 78, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:05:28] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 79, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 79, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
ERROR:Zortom:Exception on /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 79, in download_file
    print(g.digt)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/ctx.py", line 51, in __getattr__
    raise AttributeError(name) from None
AttributeError: digt
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:15:11] "[35m[1mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:16:55] "GET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:21:32] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393335353337393935353535393139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f6d712e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:23:40] "[36mGET /cdn/2f686f6d652f632f436f64652f6769746875622f74466c61736b2d496d6167652d47616c6c6572792f696e7374616e63652f7172732f313636303537393833323131343538363134363139322e3136382e322e31352e6a7067 HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/0 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    filepath=digt[filepath]
KeyError: '0'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[35m[1mGET /cdn/0 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/1 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    filepath=digt[filepath]
KeyError: '1'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[35m[1mGET /cdn/1 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    filepath=digt[filepath]
KeyError: '2'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:28:12] "[35m[1mGET /cdn/2 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/0 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '0'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[35m[1mGET /cdn/0 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/1 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '1'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[35m[1mGET /cdn/1 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '2'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:36:33] "[35m[1mGET /cdn/2 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
ERROR:Zortom:Exception on /cdn/0 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '0'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[35m[1mGET /cdn/0 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/1 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '1'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[35m[1mGET /cdn/1 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 76, in download_file
    print(type(filepath))
KeyError: '2'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:38:22] "[35m[1mGET /cdn/2 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[33mGET /blah HTTP/1.1[0m" 404 -
ERROR:Zortom:Exception on /cdn/0 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 77, in download_file
    filepath1=digt[filepath]
KeyError: '0'
ERROR:Zortom:Exception on /cdn/1 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 77, in download_file
    filepath1=digt[filepath]
KeyError: '1'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[35m[1mGET /cdn/0 HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[35m[1mGET /cdn/1 HTTP/1.1[0m" 500 -
ERROR:Zortom:Exception on /cdn/2 [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 77, in download_file
    filepath1=digt[filepath]
KeyError: '2'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:00] "[35m[1mGET /cdn/2 HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "GET /cdn/0 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "GET /cdn/2 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:40:44] "GET /cdn/1 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "GET /cdn/1.254936354262851 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "GET /cdn/1.9706000008227775 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:33] "GET /cdn/4.202459485936007 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[36mGET /cdn/1.254936354262851 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[36mGET /cdn/1.9706000008227775 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "GET /cdn/4.311080844280763 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "GET /cdn/5.060802914492827 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "GET /cdn/4.398270097586794 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:50] "[36mGET /cdn/4.202459485936007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/1.254936354262851 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/4.311080844280763 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/4.202459485936007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/5.060802914492827 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/1.9706000008227775 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "[36mGET /cdn/4.398270097586794 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "GET /cdn/4.836181721551344 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "GET /cdn/9.819127431522007 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:47:56] "GET /cdn/2.036489412529522 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/1.254936354262851 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/4.202459485936007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/5.060802914492827 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/4.311080844280763 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/4.398270097586794 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/4.836181721551344 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/9.819127431522007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/1.9706000008227775 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "GET /cdn/0.6797668772299159 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "GET /cdn/2.1720128671875436 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "GET /cdn/4.921284053349526 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:48:18] "[36mGET /cdn/2.036489412529522 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 00:50:48] "GET /cdn/1.254936354262851 HTTP/1.1" 200 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:33] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[33mGET /blah HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/1.9706000008227775 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/1.254936354262851 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/4.202459485936007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/4.311080844280763 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/5.060802914492827 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/4.398270097586794 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/9.819127431522007 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/4.836181721551344 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/2.036489412529522 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/0.6797668772299159 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/4.921284053349526 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[36mGET /cdn/2.1720128671875436 HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 21:55:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://192.168.5.2:8457 (Press CTRL+C to quit)
ERROR:Zortom:Exception on / [GET]
Traceback (most recent call last):
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c/Code/Shell/Conf1/vconf1/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 53, in home
    session.img_paths[str(random.random())]=img
AttributeError: 'SecureCookieSession' object has no attribute 'img_paths'
INFO:werkzeug:192.168.5.2 - - [18/Aug/2022 23:16:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
